### ISSUE TITLE
Update READMEs across installers to reference Project Scope Stacks in Self-Managed Backends

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-self-hosted-installers#103] opened 2023-06-06 13:34 UTC
Currently, all installer READMEs contain references to the legacy self-managed stack names (eg- my-stack). Notice there is not fully qualified stack name. With, the changes listed [here](https://www.pulumi.com/blog/project-scoped-stacks-in-self-managed-backend/) self-managed backends now contain fully qualified stack names.

- Project scoped stacks take effect automatically with new state backends (empty buckets, blobs, etc). 
- For existing state backends who want to upgrade, see https://www.pulumi.com/blog/project-scoped-stacks-in-self-managed-backend/#upgrading-existing-backends.
- available in v3.61.0 (pu/pu)

**Comment by rshade** [comment] 2024-11-04 21:28
Duplicate of #94

**Closed** 2024-11-04 21:28 UTC
Labels: resolution/duplicate, kind/engineering
